### PR TITLE
fix #10 Install opencv-python==3.4.2.17

### LINKED ISSUE #10: mybinder ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Steps to reproduce:

1. Launch https://mybinder.org/v2/gh/Fireline-Science/tello_sim/master
2. Select drone_notebook.ipynb file.
3. run import tello_sim cell

Result: (Screen capture)

image

### PR DESCRIPTION
**Pull request by kfern**
Install opencv-python version 3.4.2.17 in mybinder before setup.py

### CODE REVIEW

**Comment by sean-schaefer** [comment]
Hello, thanks for the PR.

Our package doesn't explicitly require `opencv-python`, but the `easytello` package that we use [does](https://github.com/Virodroid/easyTello/blob/master/setup.py). The python lib for opencv makes some assumptions about the system-level packages that are installed in the environment (in this case, `libGL`). I took a look at your binder and it looks like it installed `opencv-python` at version 4.

I'm not sure why the import error doesn't exist in the earlier version of opencv (maybe it didn't have a libGL requirement then) but we probably shouldn't force a lower opencv version requirement on our lib when it's really something that should be handled at the system level per-environment. Have you tried adding an [apt.txt](https://mybinder.readthedocs.io/en/latest/config_files.html#apt-txt-install-packages-with-apt-get) to your binder to make sure libGL gets installed? It looks like the package would be `libgl1-mesa-glx`. If that works it could be something we include in our repo to make for easier binder / notebook cloning.

**Comment by kfern** [comment]
Hello @sean-schaefer

Sorry, but I don't know how apt.txt works

I have added a [tests opencv_python versions](https://mybinder.org/v2/gh/kfern/tello_sim_actividades/fix-10?filepath=test_opencv_python_versions.ipynb) notebook. In this example, all versions works fine. If you run the same notebook in your repository it does not work in all cases

**Comment by sean-schaefer** [comment]
Thanks @kfern, that notebook was helpful for debugging.

There is definitely some strangeness with the opencv-python installation. In your notebook, I was able to reproduce the import error by starting the notebook and immediately running the final command to install 4.4.0.40 without running any of the other commands:
image

I made a PR (#12) to demonstrate using apt.txt to solve the issue. Can you confirm if that works for you and we'll get it merged? That will keep the solution here at the environment level rather than forcing versions for an indirect dependency.

**Comment by kfern** [comment]
@sean-schaefer This PR solves the problem. Thanks

**Pull request closed without merging**
